// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXrsi_KR7ZGHovmregUb_pTOUoZ5x96t4',
    appId: '1:575147882005:web:72822c2ec53be6a790c01c',
    messagingSenderId: '575147882005',
    projectId: 'praxis-donation-backend',
    authDomain: 'praxis-donation-backend.firebaseapp.com',
    storageBucket: 'praxis-donation-backend.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgClYi1rp2ExfcTCZ--CJbDNaGlwo7fgA',
    appId: '1:575147882005:ios:605a6a77de1022fb90c01c',
    messagingSenderId: '575147882005',
    projectId: 'praxis-donation-backend',
    storageBucket: 'praxis-donation-backend.appspot.com',
    iosClientId:
        '575147882005-kug2dq0gtb6sarfjfvebub5r09772d1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.onya_frontend',
  );
}
